/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  post?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'post'
  }
  openInNewTab?: boolean
}

export type TrustedByLogo = {
  _type: 'trustedByLogo'
  logo: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ServiceItem = {
  _type: 'serviceItem'
  title: string
  description?: string
  image?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imageSide?: 'left' | 'right'
  learnMoreLabel?: string
  learnMoreLink?: Link
}

export type HeroSection = {
  _type: 'heroSection'
  label?: string
  heading: string
  body?: string
  ctaLabel?: string
  ctaLink?: Link
  backgroundImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type FeatureItem = {
  _type: 'featureItem'
  title: string
  kicker?: string
  body?: string
  icon?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  showAccentBars?: boolean
}

export type CtaSection = {
  _type: 'ctaSection'
  heading: string
  body?: string
  buttonLabel?: string
  buttonLink?: Link
}

export type CallToAction = {
  _type: 'callToAction'
  heading: string
  text?: string
  buttonText?: string
  link?: Link
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'page'
    }
    post?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'post'
    }
    openInNewTab?: boolean
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type SchedulePage = {
  _id: string
  _type: 'schedulePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heading?: string
  description?: string
  confirmationHeading?: string
  confirmationBody?: string
  notificationEmail: string
  businessAddress?: string
  businessPhone?: string
}

export type FooterContent = {
  _id: string
  _type: 'footerContent'
  _createdAt: string
  _updatedAt: string
  _rev: string
  address?: string
  phone?: string
  badgeImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  copyrightText?: string
  legalLinks?: Array<{
    label: string
    href: string
    _key: string
  }>
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Navigation = {
  _id: string
  _type: 'navigation'
  _createdAt: string
  _updatedAt: string
  _rev: string
  navLinks?: Array<{
    label: string
    href: string
    _key: string
  }>
  ctaLabel?: string
  ctaHref?: string
}

export type WhatMakesUsDifferentPage = {
  _id: string
  _type: 'whatMakesUsDifferentPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero?: HeroSection
  featuresSectionHeading?: string
  features?: Array<
    {
      _key: string
    } & FeatureItem
  >
  bottomCta?: CtaSection
}

export type TeamPage = {
  _id: string
  _type: 'teamPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero?: HeroSection
  bottomCta?: CtaSection
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero?: HeroSection
  formHeading?: string
  formRecipientEmails: Array<string>
  contactHeading?: string
  address?: string
  phone?: string
  email?: string
  contactImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ServicesPage = {
  _id: string
  _type: 'servicesPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero?: HeroSection
  sectionTitle?: string
  services?: Array<
    {
      _key: string
    } & ServiceItem
  >
  bottomCta?: CtaSection
}

export type AboutPage = {
  _id: string
  _type: 'aboutPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  hero?: HeroSection
  hybridCoatingHeading?: string
  hybridCoatingBody?: string
  contentRows?: Array<
    {
      _key: string
    } & ServiceItem
  >
  bottomCta?: CtaSection
}

export type HomePage = {
  _id: string
  _type: 'homePage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroHeading: string
  heroBody?: string
  heroPrimaryCtaLabel?: string
  heroPrimaryCtaLink?: Link
  heroSecondaryCtaLabel?: string
  heroSecondaryCtaLink?: Link
  heroBackgroundImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  trustedByHeading?: string
  trustedByLogos?: Array<
    {
      _key: string
    } & TrustedByLogo
  >
  differentiatorHeadingRegular?: string
  differentiatorHeadingBold?: string
  differentiatorBody?: string
  differentiatorCtaLabel?: string
  differentiatorCtaLink?: Link
  differentiatorImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  blastToFinishHeading?: string
  blastToFinishBody?: string
  blastToFinishCtaLabel?: string
  blastToFinishCtaLink?: Link
  blastToFinishBackgroundImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  quickLinks?: Array<{
    label: string
    href: string
    tone?: 'primary' | 'secondary'
    _key: string
  }>
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
      post?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'person'
  }
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  firstName: string
  lastName: string
  role?: string
  isTeamMember?: boolean
  displayOrder?: number
  picture: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
  }
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | Link
  | TrustedByLogo
  | ServiceItem
  | HeroSection
  | FeatureItem
  | CtaSection
  | CallToAction
  | InfoSection
  | BlockContent
  | SchedulePage
  | FooterContent
  | SanityImageCrop
  | SanityImageHotspot
  | Navigation
  | WhatMakesUsDifferentPage
  | TeamPage
  | ContactPage
  | ServicesPage
  | AboutPage
  | HomePage
  | Settings
  | Page
  | Post
  | Person
  | Slug
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
      post?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'post'
      }
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {          link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      },      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        heading: string
        text?: string
        buttonText?: string
        link: {
          _type: 'link'
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page: string | null
          post: string | null
          openInNewTab?: boolean
        } | null
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: 'span'
            _key: string
          }>
          style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
          listItem?: 'bullet' | 'number'
          markDefs: Array<{
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
            _type: 'link'
            _key: string
          }> | null
          level?: number
          _type: 'block'
          _key: string
        }> | null
      }
  > | null
} | null
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'post'
      _updatedAt: string
    }
>
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
    listItem?: 'bullet' | 'number'
    markDefs: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }> | null
    level?: number
    _type: 'block'
    _key: string
  }> | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
} | null
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>
// Variable: teamMembersQuery
// Query: *[_type == "person" && isTeamMember == true] | order(displayOrder asc, firstName asc) {    _id,    firstName,    lastName,    role,    picture  }
export type TeamMembersQueryResult = Array<{
  _id: string
  firstName: string
  lastName: string
  role: string | null
  picture: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}>
// Variable: homePageQuery
// Query: *[_type == "homePage"][0]{    heroHeading,    heroBody,    heroPrimaryCtaLabel,    heroPrimaryCtaLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } },    heroSecondaryCtaLabel,    heroSecondaryCtaLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } },    heroBackgroundImage,    trustedByHeading,    trustedByLogos[]{ logo },    differentiatorHeadingRegular,    differentiatorHeadingBold,    differentiatorBody,    differentiatorCtaLabel,    differentiatorCtaLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } },    differentiatorImage,    blastToFinishHeading,    blastToFinishBody,    blastToFinishCtaLabel,    blastToFinishCtaLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } },    blastToFinishBackgroundImage,    quickLinks[]{ label, href, tone }  }
export type HomePageQueryResult = {
  heroHeading: string
  heroBody: string | null
  heroPrimaryCtaLabel: string | null
  heroPrimaryCtaLink: {
    _type: 'link'
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page: string | null
    post: string | null
    openInNewTab?: boolean
  } | null
  heroSecondaryCtaLabel: string | null
  heroSecondaryCtaLink: {
    _type: 'link'
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page: string | null
    post: string | null
    openInNewTab?: boolean
  } | null
  heroBackgroundImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  trustedByHeading: string | null
  trustedByLogos: Array<{
    logo: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  }> | null
  differentiatorHeadingRegular: string | null
  differentiatorHeadingBold: string | null
  differentiatorBody: string | null
  differentiatorCtaLabel: string | null
  differentiatorCtaLink: {
    _type: 'link'
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page: string | null
    post: string | null
    openInNewTab?: boolean
  } | null
  differentiatorImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  blastToFinishHeading: string | null
  blastToFinishBody: string | null
  blastToFinishCtaLabel: string | null
  blastToFinishCtaLink: {
    _type: 'link'
    linkType?: 'href' | 'page' | 'post'
    href?: string
    page: string | null
    post: string | null
    openInNewTab?: boolean
  } | null
  blastToFinishBackgroundImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  quickLinks: Array<{
    label: string
    href: string
    tone: 'primary' | 'secondary' | null
  }> | null
} | null
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage"][0]{    hero {      label, heading, body, ctaLabel,      ctaLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } },      backgroundImage    },    hybridCoatingHeading,    hybridCoatingBody,    contentRows[]{ title, description, image, imageSide, learnMoreLabel, learnMoreLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } } },    bottomCta {      heading, body, buttonLabel,      buttonLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } }    }  }
export type AboutPageQueryResult = {
  hero: {
    label: string | null
    heading: string
    body: string | null
    ctaLabel: string | null
    ctaLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
    backgroundImage: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  hybridCoatingHeading: string | null
  hybridCoatingBody: string | null
  contentRows: Array<{
    title: string
    description: string | null
    image: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
    imageSide: 'left' | 'right' | null
    learnMoreLabel: string | null
    learnMoreLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
  }> | null
  bottomCta: {
    heading: string
    body: string | null
    buttonLabel: string | null
    buttonLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
  } | null
} | null
// Variable: servicesPageQuery
// Query: *[_type == "servicesPage"][0]{    hero {      label, heading, body, ctaLabel,      ctaLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } },      backgroundImage    },    sectionTitle,    services[]{ title, description, image, imageSide, learnMoreLabel, learnMoreLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } } },    bottomCta {      heading, body, buttonLabel,      buttonLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } }    }  }
export type ServicesPageQueryResult = {
  hero: {
    label: string | null
    heading: string
    body: string | null
    ctaLabel: string | null
    ctaLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
    backgroundImage: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  sectionTitle: string | null
  services: Array<{
    title: string
    description: string | null
    image: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
    imageSide: 'left' | 'right' | null
    learnMoreLabel: string | null
    learnMoreLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
  }> | null
  bottomCta: {
    heading: string
    body: string | null
    buttonLabel: string | null
    buttonLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
  } | null
} | null
// Variable: contactPageQuery
// Query: *[_type == "contactPage"][0]{    hero {      label, heading, body,      backgroundImage    },    formHeading,    formRecipientEmails,    contactHeading,    address,    phone,    email,    contactImage  }
export type ContactPageQueryResult = {
  hero: {
    label: string | null
    heading: string
    body: string | null
    backgroundImage: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  formHeading: string | null
  formRecipientEmails: Array<string>
  contactHeading: string | null
  address: string | null
  phone: string | null
  email: string | null
  contactImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
} | null
// Variable: teamPageQuery
// Query: *[_type == "teamPage"][0]{    hero {      label, heading, body,      backgroundImage    },    bottomCta {      heading, body, buttonLabel,      buttonLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } }    }  }
export type TeamPageQueryResult = {
  hero: {
    label: string | null
    heading: string
    body: string | null
    backgroundImage: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  bottomCta: {
    heading: string
    body: string | null
    buttonLabel: string | null
    buttonLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
  } | null
} | null
// Variable: whatMakesUsDifferentPageQuery
// Query: *[_type == "whatMakesUsDifferentPage"][0]{    hero {      label, heading, body, ctaLabel,      ctaLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } },      backgroundImage    },    featuresSectionHeading,    features[]{ title, kicker, body, icon, showAccentBars },    bottomCta {      heading, body, buttonLabel,      buttonLink { ...,   _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  } }    }  }
export type WhatMakesUsDifferentPageQueryResult = {
  hero: {
    label: string | null
    heading: string
    body: string | null
    ctaLabel: string | null
    ctaLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
    backgroundImage: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    } | null
  } | null
  featuresSectionHeading: string | null
  features: Array<{
    title: string
    kicker: string | null
    body: string | null
    icon: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    showAccentBars: boolean | null
  }> | null
  bottomCta: {
    heading: string
    body: string | null
    buttonLabel: string | null
    buttonLink: {
      _type: 'link'
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page: string | null
      post: string | null
      openInNewTab?: boolean
    } | null
  } | null
} | null
// Variable: navigationQuery
// Query: *[_type == "navigation"][0]{    navLinks[]{ label, href },    ctaLabel,    ctaHref  }
export type NavigationQueryResult = {
  navLinks: Array<{
    label: string
    href: string
  }> | null
  ctaLabel: string | null
  ctaHref: string | null
} | null
// Variable: footerContentQuery
// Query: *[_type == "footerContent"][0]{    address,    phone,    badgeImage,    copyrightText,    legalLinks[]{ label, href }  }
export type FooterContentQueryResult = {
  address: string | null
  phone: string | null
  badgeImage: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  copyrightText: string | null
  legalLinks: Array<{
    label: string
    href: string
  }> | null
} | null
// Variable: schedulePageQuery
// Query: *[_type == "schedulePage"][0]{    heading,    description,    confirmationHeading,    confirmationBody,    notificationEmail,    businessAddress,    businessPhone  }
export type SchedulePageQueryResult = {
  heading: string | null
  description: string | null
  confirmationHeading: string | null
  confirmationBody: string | null
  notificationEmail: string
  businessAddress: string | null
  businessPhone: string | null
} | null

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n,\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "person" && isTeamMember == true] | order(displayOrder asc, firstName asc) {\n    _id,\n    firstName,\n    lastName,\n    role,\n    picture\n  }\n': TeamMembersQueryResult
    '\n  *[_type == "homePage"][0]{\n    heroHeading,\n    heroBody,\n    heroPrimaryCtaLabel,\n    heroPrimaryCtaLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n },\n    heroSecondaryCtaLabel,\n    heroSecondaryCtaLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n },\n    heroBackgroundImage,\n    trustedByHeading,\n    trustedByLogos[]{ logo },\n    differentiatorHeadingRegular,\n    differentiatorHeadingBold,\n    differentiatorBody,\n    differentiatorCtaLabel,\n    differentiatorCtaLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n },\n    differentiatorImage,\n    blastToFinishHeading,\n    blastToFinishBody,\n    blastToFinishCtaLabel,\n    blastToFinishCtaLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n },\n    blastToFinishBackgroundImage,\n    quickLinks[]{ label, href, tone }\n  }\n': HomePageQueryResult
    '\n  *[_type == "aboutPage"][0]{\n    hero {\n      label, heading, body, ctaLabel,\n      ctaLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n },\n      backgroundImage\n    },\n    hybridCoatingHeading,\n    hybridCoatingBody,\n    contentRows[]{ title, description, image, imageSide, learnMoreLabel, learnMoreLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n } },\n    bottomCta {\n      heading, body, buttonLabel,\n      buttonLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n }\n    }\n  }\n': AboutPageQueryResult
    '\n  *[_type == "servicesPage"][0]{\n    hero {\n      label, heading, body, ctaLabel,\n      ctaLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n },\n      backgroundImage\n    },\n    sectionTitle,\n    services[]{ title, description, image, imageSide, learnMoreLabel, learnMoreLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n } },\n    bottomCta {\n      heading, body, buttonLabel,\n      buttonLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n }\n    }\n  }\n': ServicesPageQueryResult
    '\n  *[_type == "contactPage"][0]{\n    hero {\n      label, heading, body,\n      backgroundImage\n    },\n    formHeading,\n    formRecipientEmails,\n    contactHeading,\n    address,\n    phone,\n    email,\n    contactImage\n  }\n': ContactPageQueryResult
    '\n  *[_type == "teamPage"][0]{\n    hero {\n      label, heading, body,\n      backgroundImage\n    },\n    bottomCta {\n      heading, body, buttonLabel,\n      buttonLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n }\n    }\n  }\n': TeamPageQueryResult
    '\n  *[_type == "whatMakesUsDifferentPage"][0]{\n    hero {\n      label, heading, body, ctaLabel,\n      ctaLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n },\n      backgroundImage\n    },\n    featuresSectionHeading,\n    features[]{ title, kicker, body, icon, showAccentBars },\n    bottomCta {\n      heading, body, buttonLabel,\n      buttonLink { ..., \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n }\n    }\n  }\n': WhatMakesUsDifferentPageQueryResult
    '\n  *[_type == "navigation"][0]{\n    navLinks[]{ label, href },\n    ctaLabel,\n    ctaHref\n  }\n': NavigationQueryResult
    '\n  *[_type == "footerContent"][0]{\n    address,\n    phone,\n    badgeImage,\n    copyrightText,\n    legalLinks[]{ label, href }\n  }\n': FooterContentQueryResult
    '\n  *[_type == "schedulePage"][0]{\n    heading,\n    description,\n    confirmationHeading,\n    confirmationBody,\n    notificationEmail,\n    businessAddress,\n    businessPhone\n  }\n': SchedulePageQueryResult
  }
}
